# Generated by Django 5.0.6 on 2024-06-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='products',
        ),
    ]
