# Generated by Django 5.0.6 on 2024-06-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='products',
            new_name='favoriteProducts',
        ),
    ]
