# Generated by Django 5.0.6 on 2024-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_favoriteproducts'),
        ('products', '0016_alter_product_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favoriteProducts',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
