# Generated by Django 5.0.6 on 2024-06-27 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_publishdate_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 18, 11, 7, 117844)),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
