# Generated by Django 5.0.6 on 2024-06-27 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_publishdate_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 18, 11, 50, 967662)),
        ),
    ]
