# Generated by Django 5.0.6 on 2024-06-27 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_publishdate_addfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 19, 51, 57, 903874)),
        ),
        migrations.DeleteModel(
            name='addFavorite',
        ),
    ]
