# Generated by Django 5.0.6 on 2024-06-29 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_publishdate_delete_addfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 16, 1, 24, 281994)),
        ),
    ]
