# Generated by Django 5.0.6 on 2024-06-29 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 23, 4, 58, 534135)),
        ),
    ]
