# Generated by Django 5.0.6 on 2024-07-06 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 19, 35, 44, 75412)),
        ),
    ]
