# Generated by Django 5.0.6 on 2024-08-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 15, 1, 33, 11315)),
        ),
    ]
